# Production Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["talking-points.csproj", "./"]
RUN dotnet restore "./talking-points.csproj"
COPY . .
RUN dotnet publish "./talking-points.csproj" -c Release -r linux-arm64 --self-contained false -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "talking-points.dll"]
