{{- if .Values.azureWorkloadIdentity.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: azure-wi-webhook-mutating-webhook
spec:
  admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    service:
      name: azure-wi-webhook-webhook-service
      namespace: kube-system
      path: /mutate-v1-pod
  failurePolicy: Ignore
  matchPolicy: Equivalent
  namespaceSelector: {}
  objectSelector:
    matchLabels:
      azure.workload.identity/use: "true"
  rules:
    - admissionReviewVersions:
        - v1
        - v1beta1
      apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - pods
  sideEffects: None
{{- end }}
