{{- if .Values.azureWorkloadIdentity.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: azure-wi-webhook-webhook-service
  namespace: kube-system
  labels:
    app: workload-identity-webhook
    azure-workload-identity.io/system: "true"
spec:
  ports:
    - name: webhook-server
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: workload-identity-webhook
    azure-workload-identity.io/system: "true"
{{- end }}
