import type { Metadata } from "next";
import {
  Fira_Sans_Condensed,
  Fjalla_One,
  Playfair_Display,
} from "next/font/google";
import "./styles/index.scss";
import layoutStyles from "./page.module.scss";
import Script from "next/script";
import Footer from "./components/footer";
import React from "react";
import NavWrapper from "./components/nav-wrapper";
import UserWrapper from "./components/user-context";
import { CirclePackingProvider } from "./context/circle-packing-context";

const firaSansCondensed = Fira_Sans_Condensed({
  variable: "--font-fira-sans-condensed",
  subsets: ["latin"],
  weight: "600",
});

const fjallaOne = Fjalla_One({
  variable: "--font-fjalla-one",
  subsets: ["latin"],
  weight: "400",
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSansCondensed.variable} ${fjallaOne.variable} ${playfairDisplay.variable} ${layoutStyles.bodyClassName} ${layoutStyles.padBody} container`}
      >
        <UserWrapper>
          <NavWrapper>
            <CirclePackingProvider>{children}</CirclePackingProvider>
          </NavWrapper>
        </UserWrapper>
        <Footer />
        <Script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossOrigin="anonymous"
        ></Script>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
          integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
          crossOrigin="anonymous"
        ></Script>
      </body>
    </html>
  );
}
