name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" | docker login -u ${{ secrets.AZURE_USERNAME }} --password-stdin starterpackregistry.azurecr.io

      - name: Build Frontend Docker image
        run: |
          docker buildx build --platform linux/arm64 \
            -t starterpackregistry.azurecr.io/talking-points-frontend:latest \
            -f Dockerfile .

      - name: Push Frontend Docker image
        run: |
          docker push starterpackregistry.azurecr.io/talking-points-frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" | docker login -u ${{ secrets.AZURE_USERNAME }} --password-stdin starterpackregistry.azurecr.io

      - name: Build Backend Docker image
        run: |
          cd src/server && docker buildx build --platform linux/arm64 \
            -t starterpackregistry.azurecr.io/talking-points-backend:latest \
            -f Dockerfile.prod .

      - name: Push Backend Docker image
        run: |
          docker push starterpackregistry.azurecr.io/talking-points-backend:latest
