name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . \
            --file Dockerfile \
            --tag talking-points-frontend:$TIMESTAMP
      - name: Send Webhook for Frontend
        run: |
          TIMESTAMP=$(date +%s)
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"image":"talking-points-frontend","tag":"'"$TIMESTAMP"'"}' \
            ${{ secrets.FRONTEND_WEBHOOK_URL }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . \
            --file src/server/Dockerfile.prod \
            --tag talking-points-backend:$TIMESTAMP
      - name: Send Webhook for Backend
        run: |
          TIMESTAMP=$(date +%s)
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"image":"talking-points-backend","tag":"'"$TIMESTAMP"'"}' \
            ${{ secrets.BACKEND_WEBHOOK_URL }}
