name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag talking-points-frontend:latest
      - name: Send Webhook for Frontend
        run: |
          curl -v -X POST \
            -H "Content-Type: application/json" \
            -d '{"image":"starterpackregistry.azurecr.io/talking-points-frontend","tag":"'"$TIMESTAMP"'"}' \
            ${{ secrets.FRONTEND_WEBHOOK_URL }} || echo "Webhook call failed with status $?"

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend Docker image
        run: |
          cd src/server && docker build . \
            --file Dockerfile.prod \
            --tag talking-points-backend:latest
      - name: Send Webhook for Backend
        run: |
          curl -v -X POST \
            -H "Content-Type: application/json" \
            -d '{"image":"starterpackregistry.azurecr.io/talking-points-backend","tag":"'"$TIMESTAMP"'"}' \
            ${{ secrets.BACKEND_WEBHOOK_URL }} || echo "Webhook call failed with status $?"
