name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: |
          docker login -u ${{ secrets.AZURE_USERNAME }} --password-stdin ${{ secrets.AZURE_CREDENTIALS }} starterpackregistry.azurecr.io

      - name: Build Frontend Docker image
        run: |
          docker build \
            -t starterpackregistry.azurecr.io/talking-points-frontend:latest \
            -f Dockerfile .

      - name: Push Frontend Docker image
        run: |
          docker push starterpackregistry.azurecr.io/talking-points-frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: |
          docker login -u ${{ secrets.AZURE_USERNAME }} --password-stdin ${{ secrets.AZURE_CREDENTIALS }} starterpackregistry.azurecr.io

      - name: Build Backend Docker image
        run: |
          cd src/server && docker build \
            -t starterpackregistry.azurecr.io/talking-points-backend:latest \
            -f Dockerfile.prod .

      - name: Push Backend Docker image
        run: |
          docker push starterpackregistry.azurecr.io/talking-points-backend:latest
