name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Frontend Docker image
        run: |
          az acr build \
            --image talking-points-frontend:latest \
            --registry starterpackregistry \
            --file Dockerfile .

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Backend Docker image
        run: |
          az acr build \
            --image talking-points-backend:latest \
            --registry starterpackregistry \
            --file src/server/Dockerfile.prod .
